export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
export EDITOR=vim

alias grepv='grep -v'
alias grepi='grep -i'

alias vi="vim -u NONE"

# my trusty git hacks
alias wipit='git add . && git commit -nam "WIP"'
alias unwipit='git reset --soft HEAD~ && git reset'
alias gap='git add --patch'
alias gbgone='git branch -vv | grep ": gone"'
alias gdw='git diff -w'
alias gds='git diff --staged'

# my trusty docker hakcs
alias docker_remove_all_containers='docker rm $(docker ps -a -q)'
alias docker_remove_all_images='docker rmi $(docker images -q)'
alias docker_remove_all_the_things='docker_remove_all_containers; docker_remove_all_images'

# quick aliases to help set per-repo emails for git (for use with "useConfigOnly = true" in gitconfig)
alias set_git_email_school='git config --local user.email "jastribl@edu.uwaterloo.ca"'
alias set_git_email_personal='git config --local user.email "justinastribling@gmail.com"'

# easy way to open a PR (defaults to PR against develop)
function PR () {
    REPO_URL=`git remote -v | grep fetch | head -1 | cut -f2 | cut -d' ' -f1 | sed -e's/git@/http:\/\//' -e's/\.git$//' | sed -E 's/(\/\/[^:]*):/\1\//'`
    BASE_BRANCH=${1:-develop}
    COMPARE_BRANCH=`git symbolic-ref --short HEAD`
    PR_URL="$REPO_URL/compare/$BASE_BRANCH...$COMPARE_BRANCH?expand=1"
    if [[ `uname -s` = "Darwin" ]]; then
        open "$PR_URL"
    else
        echo "$PR_URL"
    fi
}


if [[ -e ~/.bashrc.local ]]; then
    source ~/.bashrc.local
fi
