export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
export EDITOR=vim

alias grepv='grep -v'
alias grepi='grep -i'

# my trusty git hacks
alias wipit='git add . && git commit -nam "WIP"'
alias unwipit='git reset --soft HEAD~ && git reset'
alias gap='git add --patch'
alias gbgone='git branch -vv | grep ": gone"'
alias gdw='git diff -w'

# quick aliases to help set per-repo emails for git (for use with "useConfigOnly = true" in gitconfig)
alias set_git_email_textnow='git config --local user.email "justin.stribling@textnow.com"'
alias set_git_email_school='git config --local user.email "jastribl@edu.uwaterloo.ca"'
alias set_git_email_personal='git config --local user.email "justinastribling@gmail.com"'
alias set_git_email_uber='git config --local user.email "justin.stribling@uber.com"'

if [[ -e ~/.bashrc.local ]]; then
    source ~/.bashrc.local
fi
