" load local pre-settings
if filereadable(expand('~/.vim/vimrc-pre-local.vim'))
    source ~/.vim/vimrc-pre-local.vim
end

" load plugin settings
if filereadable(expand('~/.vim/plugins.vim'))
    source ~/.vim/plugins.vim
end

" load config
if filereadable(expand('~/.vim/config.vim'))
	source ~/.vim/config.vim
end
