# Path to your oh-my-zsh installation.
export ZSH=~/.oh-my-zsh

ZSH_THEME="robbyrussell"

plugins=(git rails per-directory-history vagrant go docker docker-compose tmux)

source $ZSH/oh-my-zsh.sh
source ~/.bashrc
