# Path to your oh-my-zsh installation.
export ZSH=~/.oh-my-zsh

ZSH_THEME="robbyrussell"

plugins=(git brew rails npm per-directory-history vagrant tmux go docker)

source $ZSH/oh-my-zsh.sh
source ~/.bashrc

