export PATH="$HOME/bin:$HOME/vim81/bin:$PATH:$HOME/diff-so-fancy"

[ -z "$TMUX"  ] && { tmux attach || tmux new-session;}

# Add db2 stuff
alias db2c='bash -c "source ~db2inst2/sqllib/db2profile && rlwrap db2"'

# Add silver searcher
export PATH="$PATH:/u6/jastribling/Github/the_silver_searcher/bin/"
