alias reindex_spotlight='sudo mdutil -E -i on /'
alias remove_ds_store_files='sudo find . -name '.DS_Store' -type f -delete'

# use vim installed through brew, not the built-in vim
alias vim='/usr/local/bin/vim'

# my trusty brew hacks
alias brew_dep_list='brew list | while read cask; do echo -n $fg[yellow] $cask $fg[red]; brew deps $cask | awk '"'"'{printf(" %s ", $0)}'"'"'; echo ""; done'
alias brew_outdated='brew update; brew outdated; brew cask outdated;'
alias brew_upgrade_all='brew upgrade; brew cask upgrade;'
alias brew_cleanup_all='brew cleanup; brew cask cleanup;'

alias copy_location='pwd | pbcopy'
alias cd_clipboard='cd `pbpaste`'

# some simple aliases to get places
alias cd_desktop='cd ~/Desktop'
alias cd_documents='cd ~/Documents'
alias cd_git='cd ~/Github'
alias cd_downloads='cd ~/Downloads'
alias cd_drive='cd ~/Google\ Drive/'
alias cd_go='cd $GOPATH/src'

alias cddesktop='cd_desktop'
alias cddocuments='cd_documents'
alias cdgit='cd_git'
alias cddownloads='cd_downloads'
alias cddrive='cd_drive'
alias cdgo='cd_go'

function pandoc_latex() {
    pandoc ${1} --latex-engine=`which pdflatex` -V geometry:margin=1.00in --table-of-contents --number-sections -o ${2}
}

# Open man page as PDF
function manpdf() {
 man -t "${1}" | open -f -a /Applications/Preview.app/
}

if command -v brew >/dev/null 2>&1; then
    # Load rupa's z if installed
    [ -f "$(brew --prefix)/etc/profile.d/z.sh" ] && source "$(brew --prefix)/etc/profile.d/z.sh"
fi
