alias reindex_spotlight='sudo mdutil -E -i on /'
alias find_ds_store_files="find . -name '.DS_Store' -type f"
alias remove_ds_store_files="sudo find . -name '.DS_Store' -type f -delete"

# my trusty brew hacks
alias brew_dep_list='brew list | while read cask; do echo -en "\e[33m $cask \e[31m"; brew deps $cask | awk '"'"'{printf(" %s ", $0)}'"'"'; echo ""; done'
alias brew_outdated='brew update; brew outdated; brew cask outdated;'

alias copy_location='pwd | pbcopy'
alias cd_clipboard='cd `pbpaste`'

# some simple aliases to get places
alias cd_desktop='cd ~/Desktop'
alias cd_documents='cd ~/Documents'
alias cd_git='cd ~/Github'
alias cd_downloads='cd ~/Downloads'
alias cd_drive='cd ~/Google\ Drive/'
alias cd_go='cd $GOPATH/src'
alias cd_pictures='cd ~/Pictures'

alias cddesktop='cd_desktop'
alias cddocuments='cd_documents'
alias cdgit='cd_git'
alias cddownloads='cd_downloads'
alias cddrive='cd_drive'
alias cdgo='cd_go'
alias cdpictures='cd_pictures'

PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"

# Open man page as PDF
function manpdf() {
    man -t "${1}" | open -f -a /Applications/Preview.app/
}
