alias ssh_ece='ssh jastribl@ecelinux4.uwaterloo.ca'
alias ssh_ece_tesla='ssh jastribl@ecetesla.uwaterloo.ca'
alias ssh_cs='ssh jastribl@ubuntu1604-000.student.cs.uwaterloo.ca'
alias ssh_ugster='ssh_cs -t "ssh ugster05.student.cs.uwaterloo.ca"'
alias ssh_lifeofapunter='ssh lifeofap@23.91.70.29'
alias ssh_justin_server='ssh -i ~/.ssh/justins-server.pem ubuntu@34.234.169.130'
alias ssh_fydp='ssh e0001337@192.168.11.12'
alias ssh_pi='ssh pi@raspberrypijs.local'

# Golang setup
export GOPATH=$HOME/golang
export GOROOT=/usr/local/opt/go/libexec
export GOBIN=$GOPATH/bin
export PATH=$PATH:$GOPATH
export PATH=$PATH:$GOROOT/bin:$GOBIN

source ~/.bashrc.plugables/osx/bashrc

# added by travis gem
[ -f /Users/justinstribling/.travis/travis.sh ] && source /Users/justinstribling/.travis/travis.sh
