alias ssh_ece='ssh jastribl@ecelinux.uwaterloo.ca'
alias ssh_cs='ssh jastribl@linux.student.cs.uwaterloo.ca'
alias ssh_lifeofapunter='ssh lifeofap@23.91.70.29'
alias ssh_justin_server='ssh -i ~/.ssh/justins-server.pem ubuntu@34.234.169.130'

# use vim installed through brew, not the built-in vim
alias vim='/usr/local/bin/vim'
alias vi="vim -u NONE"

# export VAGRANT_CWD=~/Documents/GitHub/LOFP

# turn php-unit coverage off and on
alias coverageoff='mv /usr/local/etc/php/5.6/conf.d/ext-xdebug.ini /usr/local/etc/php/5.6/conf.d/ext-xdebug.ini.bk'
alias coverageon='mv /usr/local/etc/php/5.6/conf.d/ext-xdebug.ini.bk /usr/local/etc/php/5.6/conf.d/ext-xdebug.ini'

# quick commands for unit testing php
alias test='coverageoff;vendor/bin/phpunit -c tests/phpunit.xml'
alias testonly='coverageoff;vendor/bin/phpunit -c tests/phpunit.xml --filter '
alias cover='coverageon;vendor/bin/phpunit -c tests/phpunit.xml --coverage-html ./coverage'
alias coveronly='coverageon;vendor/bin/phpunit -c tests/phpunit.xml --coverage-html ./coverage --filter '

function pandoc_latex() {
    pandoc ${1} --latex-engine=`which pdflatex` -V geometry:margin=1.00in --table-of-contents --number-sections -o ${2}
}
